### PR TITLE
fix: check and raise error for insecure context

### LINKED ISSUE #73: 💡 [REQUEST] - Implement a check on function availability
### Summary

It would be nice to users of the package, if there where some checks on the availability of some of the functions that could be unavailable.
This check could print some more verbose error message that would help in debugging.

### Basic Example

Instead of getting;
```js
TypeError: Cannot read properties of undefined (reading 'digest')
``` 
when calling `window.crypto.subtle.digest('SHA-256', bytes)`.
We could print `Error: The context/environment is not secure, and does not support the 'crypto.subtle' module. See: https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle for details`

I believe there could be more examples like this:
- TextEncoder?
- 

### Drawbacks

None

### Unresolved questions

_No response_

### Implementation PR

_No response_

### Reference Issues

#72

### PR DESCRIPTION
**Pull request by soofstad**
## What does this pull request change?
- Create a check for availability of `crypto.subtle` and throw error if missing
- Update testing dependencies
- Remove unnecessary context wrapper in tests
- Added test for "unsecure-environment"

## Why is this pull request needed?
see #73 

## Issues related to this change
closes #73

### CODE REVIEW

File: src/pkceUtils.ts [hunk 1]
```diff
@@ -24,6 +24,11 @@ export function generateRandomString(length: number): string {
 export async function generateCodeChallenge(codeVerifier: string): Promise<string> {
   const encoder = new TextEncoder()
   const bytes: Uint8Array = encoder.encode(codeVerifier) // Encode the verifier to a byteArray
+  if (!window.crypto.subtle?.digest) {
+    throw new Error(
+      "The context/environment is not secure, and does not support the 'crypto.subtle' module. See: https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle for details"
+    )
+  }
```
Comment (sebastianvitterso) [inline src/pkceUtils.ts:31]: I guess you could check this in the start of the function, no? No need to make an encoder or encode the verifier if we're just gonna throw an exception.

File: tests/unsecure-environment.test.tsx
Comment (sebastianvitterso) [inline tests/unsecure-environment.test.tsx:1]: In English, the word for "not secure" is **in**secure, not **un**secure. https://english.stackexchange.com/a/19655 ✌️

**Review by sebastianvitterso — DISMISSED** [review]
Two nitpicks, looks good!
