### PR TITLE
Fix: Reset error state after successful token response

### LINKED ISSUE #221: Bug: Error state should be updated after each request
Currently, the error state gets set when there is an error during the OAuth workflow. For example, the error state is set when there is an error while fetching the new access token. However, we do not reset the error state when the new access token is fetched successfully. 

## Steps To Reproduce
1. The log-in workflow is successful. We have valid access and refresh tokens.
2. While renewing the expired access token, the error occurs, and the error state is set.
3. During the next check, the request was successful, and both access and refresh tokens were retrieved successfully. Although the error state doesn't get updated, it has the stale value. It should be set to `null`.

## The current behaviour
`error` state variable is never updated again.

## The expected behaviour
`error` state variable should be updated after each request

### PR DESCRIPTION
**Pull request by swarupbam**
## What does this pull request change?
Currently, the error state is not cleared after the successful token response. The error state gets set when there is an error while getting the token. However, the error state is not cleared even if the subsequent requests were successful.

## Why is this pull request needed?
If anyone uses the `error` property to display the error. The error will always be displayed since it is not cleared after the successful token request.

## Issues related to this change
closes #221

### CODE REVIEW

File: src/AuthContext.tsx [hunk 1]
```diff
@@ -130,6 +130,7 @@ export const AuthProvider = ({ authConfig, children }: IAuthProvider) => {
         setRefreshTokenExpire(epochAtSecondsFromNow(refreshTokenExpiresIn))
       }
     }
+    setError(null);
```
Comment (swarupbam) [inline src/AuthContext.tsx:133]: The function `handleTokenResponse` gets called when the access token is fetched for the first time, and during the refresh token flow. Hence, this seems the appropriate place to reset the error state.

**Review by soofstad — DISMISSED** [review]
Agreed! Thanks for the contribution :slightly_smiling_face:

**Comment by swarupbam** [comment]
> Ah, I see that the linting checks fail. Please run pre-commit locally and they should get fixed

@soofstad Got it. I have fixed it.

**Review by soofstad — APPROVED** [review]
Good job :+1:
