### PR TITLE
fix: always decode idToken

### LINKED ISSUE #74: 💡 [REQUEST] - Enable separate decoding steps for token/id_token
### Summary

My OAuth provider uses `id_token` as the JWT instead of `token`, but `react-oauth2-code-pkce`'s `AuthContext` tries to decode `token` first, and fails immediately without getting to `id_token`:

https://github.com/soofstad/react-oauth2-pkce/blob/4ada57fbdc873606e1705a03a0e8e71e7c3bbf66/src/AuthContext.tsx#L121-L126

https://github.com/soofstad/react-oauth2-pkce/blob/4ada57fbdc873606e1705a03a0e8e71e7c3bbf66/src/AuthContext.tsx#L233-L239

If they were decoded separately, I could at least use `idTokenData`. My current workaround is to disable `decodeToken`, and parse `idToken` with my own decoder.

#### Option 1: Decode the tokens separately

```typescript
if (decodeToken) {
  try {
    setTokenData(decodeJWT(token))
  } catch (e) {
    setError((e as Error).message)
  }

  try {
    if (idToken) setIdTokenData(decodeJWT(idToken))
  } catch (e) {
    setError((e as Error).message)
  }
}
```

#### Option 2: Add a separate config flag to decode `idToken`

```typescript
if (decodeToken) {
  try {
    setTokenData(decodeJWT(token))
  } catch (e) {
    setError((e as Error).message)
  }
}
if (decodeIdToken) {
  try {
    if (idToken) setIdTokenData(decodeJWT(idToken))
  } catch (e) {
    setError((e as Error).message)
  }
}
``` 

#### Option 1's Drawbacks

It potentially performs unnecessary work trying to decode `token` when only `idToken` is needed.  If `token` decoding fails, an error is shown in the browser console, which could annoy developers.

#### Option 2's Drawbacks

It's extra code/config to handle.

### Unresolved questions

_No response_

### Implementation PR

_No response_

### Reference Issues

_No response_

### PR DESCRIPTION
**Pull request by soofstad**
## What does this pull request change?
- Always decode idToken

## Why is this pull request needed?
- idToken is always a JWT, per https://openid.net/specs/openid-connect-core-1_0.html#IDToken
  Therefore, we can always decode it. This allows for getting `idTokenData` even if the `accessToken` is not a JWT.

> **Note**
>Try catch on idToken decode _should_ not be needed. But this would potentially be a BREAKING CHANGE if we skipped it. And I think it's good to be forgiving with these "non-crucial" functionality.

## Issues related to this change
closes #74

### CODE REVIEW

File: src/AuthContext.tsx [hunk 1]
```diff
@@ -118,11 +118,15 @@ export const AuthProvider = ({ authConfig, children }: IAuthProvider) => {
     const refreshTokenExpiresIn = config.refreshTokenExpiresIn ?? getRefreshExpiresIn(tokenExpiresIn, response)
     setRefreshTokenExpire(epochAtSecondsFromNow(refreshTokenExpiresIn))
     setIdToken(response.id_token)
+    try {
+      if (response.id_token) setIdTokenData(decodeJWT(response.id_token))
+    } catch (e) {
+      setError(`Failed to decode idToken: ${(e as Error).message}`)
```
Comment (sebastianvitterso) [inline src/AuthContext.tsx:124]: Note that this is also a breaking change, because it might now get an error trying to decode it, and setting this error in the state will show an error in all applications that prioritize authErrors.

Comment (soofstad) [reply src/AuthContext.tsx]: Agreed. Exposed "error" value should only be used for fatal errors.
Did a `console.warn` here instead
