### PR TITLE
fix: make sure main useEffect handles being fired twice

### LINKED ISSUE #50: Bug: When developing with <React.StrictMode> in React 18, will get an error because the same auth code is used twice
With [Strict Mode](https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state) starting in React 18, whenever a component mounts in development, React will simulate immediately unmounting and remounting the component.

As a result, the same auth code will be sent to the auth provider twice, and the second time will get an error.

As React document mentions, it requires components to be resilient to effects being mounted and destroyed multiple times.

## Steps To Reproduce

1. 
`root.render(
<React.StrictMode>
  <AuthProvider authConfig={authConfig}>
        <LoginInfo />
      </AuthProvider>
  </React.StrictMode>
);`

2. The error will appear

## The current behavior
The useEffect() in AuthProvider is fired twice, and the same auth code is sent to the auth provider twice.

## The expected behavior
The same auth code should not be sent to the auth provider twice.

Btw, I am not a front-end developer, so maybe my understanding of the error is not correct.

### PR DESCRIPTION
**Pull request by soofstad**
## What does this pull request change?
- Ensure main useEffect can be fired twice with the same state

## Why is this pull request needed?
- Multiple token fetches with the same code will thow

## Issues related to this change

closes #50

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -102,22 +102,24 @@ const container = document.getElementById('root')
...
-        <a href="https://github.com/soofstad/react-oauth2-pkce">https://github.com/soofstad/react-oauth2-pkce</a>
-      </p>
-      <p>
-        NPM:{' '}
-        <a href="https://www.npmjs.com/package/react-oauth2-code-pkce">
-          https://www.npmjs.com/package/react-oauth2-code-pkce
-        </a>
-      </p>
+  <React.StrictMode>
+    <div style={{}}>
```
Comment (sebastianvitterso) [inline src/index.js:106]: Not sure what the outermost div is doing anymore, I think it can be omitted.

**Review by sebastianvitterso — APPROVED** [review]
Looks good!

File: src/index.js (hunk 1 above)
Comment (soofstad) [reply src/index.js]: Fixed!
